[project]
name = "ahl"
version = "0.1.0"
description = "AHL Datasette Application"
requires-python = ">=3.11"
dependencies = [
    "datasette==1.0a3",
    "requests",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "ruff",
    "ty",
]